// Clean implementation using JSON for data storage
const fs = require('fs');
const path = require('path');

const HITBOX_CONFIG_FILE = path.join(__dirname, '../scripts/hitbox-config.js');
const JSON_CONFIG_FILE = path.join(__dirname, '../scripts/hitbox-config.json');

/**
 * Load the current configuration from JSON
 */
function loadConfig() {
    // Initialize from existing JS file if JSON doesn't exist
    if (!fs.existsSync(JSON_CONFIG_FILE)) {
        console.log('Initializing JSON config from JS file...');
        const jsContent = fs.readFileSync(HITBOX_CONFIG_FILE, 'utf8');
        
        const config = {
            flips: {},
            scales: {},
            hitboxes: {},
            shadows: {}
        };
        
        // Extract data using eval (safe since we control the file)
        try {
            // Create a sandbox to safely extract the data
            const sandbox = {};
            const configExtract = jsContent.replace('var hitboxConfig = ', 'sandbox.hitboxConfig = ');
            eval(configExtract);
            
            if (sandbox.hitboxConfig) {
                config.flips = sandbox.hitboxConfig.flips || {};
                config.scales = sandbox.hitboxConfig.scales || {};
                config.hitboxes = sandbox.hitboxConfig.hitboxes || {};
                config.shadows = sandbox.hitboxConfig.shadows || {};
            }
        } catch (e) {
            console.log('Could not extract from JS, using defaults');
        }
        
        fs.writeFileSync(JSON_CONFIG_FILE, JSON.stringify(config, null, 2));
        return config;
    }
    
    return JSON.parse(fs.readFileSync(JSON_CONFIG_FILE, 'utf8'));
}

/**
 * Save configuration to JSON
 */
function saveConfig(config) {
    fs.writeFileSync(JSON_CONFIG_FILE, JSON.stringify(config, null, 2));
}

/**
 * Generate the JavaScript file from JSON config
 */
function generateJsFile(config) {
    let js = `// Hitbox and Shadow Configuration for Enemies
// This file is generated by the sprite editor and loaded by the game
// Last updated: ${new Date().toISOString()}

console.log('hitbox-config.js is loading...');

// Check if hitboxConfig already exists to avoid redeclaration
if (typeof hitboxConfig === 'undefined') {
    console.log('Creating hitboxConfig object...');
    var hitboxConfig = {
    loaded: false,
    
    // Load configuration (called when game starts)
    load: function() {
        this.loaded = true;
        console.log('Hitbox configuration loaded');
        console.log('Available scales:', this.scales);
        console.log('Available hitboxes:', Object.keys(this.hitboxes));
        return true;
    },
    
    // Flip configurations - used for initial sprite orientation
    flips: ${JSON.stringify(config.flips, null, 8).replace(/^/gm, '    ').trim()},
    
    // Scale configurations for sprites
    scales: ${JSON.stringify(config.scales, null, 8).replace(/^/gm, '    ').trim()},
    
    // Hitbox configurations for each enemy type
    hitboxes: ${JSON.stringify(config.hitboxes, null, 8).replace(/^/gm, '    ').trim()},
    
    // Shadow configurations for each enemy type
    shadows: ${JSON.stringify(config.shadows, null, 8).replace(/^/gm, '    ').trim()},
    
    // Helper function to get scale configuration
    getScale: function(spriteType) {
        return this.scales[spriteType] || 1.0;
    },
    
    // Helper function to apply scale
    applyScale: function(sprite, spriteType) {
        const scale = this.getScale(spriteType);
        console.log(\`[HITBOX CONFIG] Applying scale for \${spriteType}: \${scale}\`);
        console.log(\`[HITBOX CONFIG] Sprite scale before: \${sprite.scaleX}\`);
        sprite.setScale(scale);
        console.log(\`[HITBOX CONFIG] Sprite scale after: \${sprite.scaleX}\`);
        return scale;
    },
    
    // Helper function to apply hitbox configuration
    applyHitbox: function(enemy, enemyType) {
        const config = this.hitboxes[enemyType];
        if (config) {
            console.log(\`[HITBOX] Applying for \${enemyType}:\`, config);
            console.log(\`[HITBOX] Sprite info - Scale: \${enemy.scaleX}, Origin: (\${enemy.originX}, \${enemy.originY})\`);
            console.log(\`[HITBOX] Sprite dimensions - Width: \${enemy.width}, Height: \${enemy.height}\`);
            console.log(\`[HITBOX] Display dimensions - Width: \${enemy.displayWidth}, Height: \${enemy.displayHeight}\`);
            
            // The sprite editor saves offsets in unscaled sprite coordinates
            // Phaser's body.setOffset() always uses unscaled coordinates
            // DO NOT divide by scale - apply directly
            enemy.body.setSize(config.width, config.height);
            enemy.body.setOffset(config.offsetX, config.offsetY);
            
            console.log(\`[HITBOX] Applied - Size: \${config.width}x\${config.height}, Direct offset: (\${config.offsetX}, \${config.offsetY})\`);
            console.log(\`[HITBOX] Body position - X: \${enemy.body.x}, Y: \${enemy.body.y}\`);
            return true;
        }
        console.log(\`[HITBOX] No config found for \${enemyType}\`);
        return false;
    },
    
    // Helper function to get shadow configuration
    getShadow: function(enemyType) {
        return this.shadows[enemyType] || this.shadows.default;
    },
    
    // Update configuration from sprite editor export
    updateFromEditor: function(editorData) {
        if (editorData.scales) {
            Object.assign(this.scales, editorData.scales);
        }
        if (editorData.hitboxes) {
            Object.assign(this.hitboxes, editorData.hitboxes);
        }
        if (editorData.shadows) {
            Object.assign(this.shadows, editorData.shadows);
        }
    }
};

    // Make available globally if in browser/Electron
    if (typeof window !== 'undefined') {
        window.hitboxConfig = hitboxConfig;
    }

    // Export for Node.js/require
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = hitboxConfig;
    }
    
    console.log('hitboxConfig created successfully');
    console.log('Grim hitbox:', hitboxConfig.hitboxes.grim);
} else {
    console.log('hitboxConfig already exists, skipping creation');
} // End of if (typeof hitboxConfig === 'undefined')

console.log('hitbox-config.js finished loading');
console.log('Flip configuration for grim:', hitboxConfig.flips.grim);`;
    
    return js;
}

/**
 * Update hitbox configuration - CLEAN VERSION
 * @param {Object} hitboxes - Hitbox updates
 * @param {Object} shadows - Shadow updates
 * @param {Object} scales - Scale updates  
 * @param {Object} flips - Flip updates
 */
function updateHitboxConfig(hitboxes, shadows, scales, flips) {
    console.log('updateHitboxConfig (CLEAN) called with:', {
        hitboxCount: Object.keys(hitboxes || {}).length,
        shadowCount: Object.keys(shadows || {}).length,
        scaleCount: Object.keys(scales || {}).length,
        flipCount: Object.keys(flips || {}).length
    });
    
    try {
        // Load current configuration
        const config = loadConfig();
        
        // Apply updates - simple Object.assign, no regex, no parsing
        if (flips && Object.keys(flips).length > 0) {
            console.log('Updating flips:', flips);
            Object.assign(config.flips, flips);
        }
        
        if (scales && Object.keys(scales).length > 0) {
            console.log('Updating scales:', scales);
            Object.assign(config.scales, scales);
        }
        
        if (hitboxes && Object.keys(hitboxes).length > 0) {
            console.log('Updating hitboxes:', hitboxes);
            Object.assign(config.hitboxes, hitboxes);
        }
        
        if (shadows && Object.keys(shadows).length > 0) {
            console.log('Updating shadows:', shadows);
            Object.assign(config.shadows, shadows);
        }
        
        // Save to JSON
        saveConfig(config);
        
        // Generate JS file
        const jsContent = generateJsFile(config);
        fs.writeFileSync(HITBOX_CONFIG_FILE, jsContent);
        
        console.log('✅ Configuration updated successfully');
        
        // Verification
        console.log('Verification:');
        if (config.flips.grim) {
            console.log(`  grim flip: ${JSON.stringify(config.flips.grim)}`);
        }
        if (config.hitboxes.grim) {
            console.log(`  grim hitbox: ${JSON.stringify(config.hitboxes.grim)}`);
        }
        if (config.hitboxes.orb) {
            console.log(`  orb hitbox: ${JSON.stringify(config.hitboxes.orb)}`);
        }
        
    } catch (error) {
        console.error('❌ Error updating hitbox-config.js:', error);
        throw error;
    }
}

module.exports = updateHitboxConfig;

// Test if run directly
if (require.main === module) {
    console.log('\n=== Testing CLEAN updateHitboxConfig ===\n');
    
    // Test with just flip updates (what causes corruption with regex)
    updateHitboxConfig(
        {}, // no hitbox updates
        {}, // no shadow updates
        {}, // no scale updates
        { 
            'grim': { flipX: false, flipY: false },
            'orb': { flipX: true, flipY: false }
        }
    );
    
    console.log('\n=== Test complete! ===');
    console.log('Check hitbox-config.js - there should be NO corruption.');
    console.log('Check hitbox-config.json for the clean data storage.');
}