// Hitbox and Shadow Configuration for Enemies
// This file is generated by the sprite editor and loaded by the game
// Last updated: Auto-generated

// Check if hitboxConfig already exists to avoid redeclaration
if (typeof hitboxConfig === 'undefined') {
    var hitboxConfig = {
    loaded: false,
    
    // Load configuration (called when game starts)
    load: function() {
        this.loaded = true;
        console.log('Hitbox configuration loaded');
        return true;
    },
    
    // Hitbox configurations for each enemy type
    hitboxes: {
        // Forest enemies
        mushroom: { width: 80, height: 30, offsetX: 35, offsetY: 8 ,
        cactuse: { width: 19, height: 20, offsetX: 7, offsetY: 3 ,
        blip: { width: 30, height: 30, offsetX: 34, offsetY: 10 ,
        orb: { width: 30, height: 30, offsetX: 17, offsetY: 17 }
    }
    }
    },
        tree: { width: 26, height: 39, offsetX: 3, offsetY: 12 },
        giantfly: { width: 28, height: 28, offsetX: 2, offsetY: 2 },
        squirrel: { width: 28, height: 28, offsetX: 2, offsetY: 2 },
        redpanda: { width: 28, height: 28, offsetX: 2, offsetY: 2 },
        
        // Cave enemies
        golem: { width: 60, height: 50, offsetX: 15, offsetY: 10 },
        'golem-blue': { width: 60, height: 50, offsetX: 15, offsetY: 10 },
        'golem-orange': { width: 60, height: 50, offsetX: 15, offsetY: 10 },
        slime: { width: 40, height: 40, offsetX: 10, offsetY: 10 },
        kobold: { width: 48, height: 42, offsetX: 20, offsetY: 8 },
        brainmole: { width: 28, height: 28, offsetX: 2, offsetY: 2 },
        intellectdevourer: { width: 26, height: 26, offsetX: 3, offsetY: 3 },
        bloboid: { width: 50, height: 30, offsetX: 15, offsetY: 2 },
        
        // Desert enemies
        cobra: { width: 24, height: 28, offsetX: 4, offsetY: 2 },
        cactuse: { width: 19, height: 20, offsetX: 7, offsetY: 3 },
        armadillo: { width: 28, height: 24, offsetX: 2, offsetY: 4 },
        bat: { width: 60, height: 40, offsetX: 45, offsetY: 55 },
        darkbat: { width: 50, height: 40, offsetX: 7, offsetY: 12 },
        soul: { width: 60, height: 60, offsetX: 18, offsetY: 18 },
        fireworm: { width: 70, height: 50, offsetX: 10, offsetY: 20 },
        summoner: { width: 80, height: 100, offsetX: 40, offsetY: 20 },
        
        // Castle enemies
        'castle-knight': { width: 30, height: 45, offsetX: 15, offsetY: 20 },
        'castle-rogue': { width: 30, height: 45, offsetX: 15, offsetY: 20 },
        'castle-soldier': { width: 30, height: 45, offsetX: 17, offsetY: 20 },
        'castle-bladekeeper': { width: 40, height: 55, offsetX: 12, offsetY: 15 },
        'castle-squire': { width: 30, height: 45, offsetX: 17, offsetY: 20 },
        
        // Grave enemies
        yellowskeleton: { width: 40, height: 50, offsetX: 28, offsetY: 14 },
        skeletonseeker: { width: 60, height: 80, offsetX: 30, offsetY: 40 },
        clubimp: { width: 30, height: 40, offsetX: 15, offsetY: 10 },
        axeimp: { width: 30, height: 40, offsetX: 15, offsetY: 10 },
        wraith: { width: 40, height: 50, offsetX: 12, offsetY: 7 },
        flyingdemon: { width: 50, height: 40, offsetX: 7, offsetY: 12 },
        
        // Lava enemies
        fireslime: { width: 40, height: 40, offsetX: 10, offsetY: 10 },
        orangegolem: { width: 60, height: 50, offsetX: 15, offsetY: 10 },
        
        // Other enemies
        sorcerer: { width: 60, height: 80, offsetX: 10, offsetY: 0 },
        
        // Bosses
        'obelisk-boss': { width: 150, height: 200, offsetX: 75, offsetY: 50 },
        'archer-boss': { width: 60, height: 80, offsetX: 45, offsetY: 40 },
        'demon-slime-boss': { width: 80, height: 80, offsetX: 40, offsetY: 40 },
        'eyelor': { width: 100, height: 100, offsetX: 50, offsetY: 50 },
        'nekros': { width: 80, height: 100, offsetX: 40, offsetY: 30 },
        'voidkin': { width: 70, height: 90, offsetX: 35, offsetY: 20 },
        'kingNothing': { width: 90, height: 110, offsetX: 45, offsetY: 20 },
        
        // Homunculi characters
        'blip': { width: 30, height: 30, offsetX: 15, offsetY: 5 },
        'orb': { width: 30, height: 30, offsetX: 15, offsetY: 15 },
        'wizard': { width: 40, height: 50, offsetX: 20, offsetY: 15 },
        'grim': { width: 40, height: 50, offsetX: 20, offsetY: 15 }
    },
    
    // Shadow configurations for each enemy type
    shadows: {
        // Default shadow settings
        default: { width: 40, height: 12, offsetX: 0, offsetY: 30, alpha: 0.5 ,
        cactuse: { width: 14, height: 6, offsetX: 0, offsetY: 30, alpha: 0.5 ,
        blip: { width: 81, height: 30, offsetX: 0, offsetY: 30, alpha: 0.5 }
    }
    },
        cactuse: { width: 14, height: 6, offsetX: 0, offsetY: 30, alpha: 0.5 },
        
        // Forest enemies
        mushroom: { width: 50, height: 15, offsetX: 0, offsetY: 20, alpha: 0.5 },
        tree: { width: 35, height: 10, offsetX: 0, offsetY: 35, alpha: 0.5 },
        giantfly: { width: 30, height: 8, offsetX: 0, offsetY: 25, alpha: 0.4 },
        squirrel: { width: 25, height: 8, offsetX: 0, offsetY: 20, alpha: 0.5 },
        redpanda: { width: 30, height: 10, offsetX: 0, offsetY: 20, alpha: 0.5 },
        
        // Larger enemies have bigger shadows
        golem: { width: 60, height: 18, offsetX: 0, offsetY: 40, alpha: 0.6 },
        'golem-blue': { width: 60, height: 18, offsetX: 0, offsetY: 40, alpha: 0.6 },
        'golem-orange': { width: 60, height: 18, offsetX: 0, offsetY: 40, alpha: 0.6 },
        'castle-knight': { width: 35, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        'castle-rogue': { width: 35, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        'castle-soldier': { width: 35, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        'castle-bladekeeper': { width: 40, height: 14, offsetX: 0, offsetY: 38, alpha: 0.5 },
        'castle-squire': { width: 35, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        
        // Grave enemies shadows
        yellowskeleton: { width: 35, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        skeletonseeker: { width: 40, height: 14, offsetX: 0, offsetY: 40, alpha: 0.5 },
        clubimp: { width: 28, height: 10, offsetX: 0, offsetY: 30, alpha: 0.5 },
        axeimp: { width: 28, height: 10, offsetX: 0, offsetY: 30, alpha: 0.5 },
        wraith: { width: 35, height: 10, offsetX: 0, offsetY: 35, alpha: 0.4 },
        
        // Desert enemies shadows
        cobra: { width: 25, height: 8, offsetX: 0, offsetY: 20, alpha: 0.5 },
        cactuse: { width: 19, height: 20, offsetX: 7, offsetY: 3, alpha: 0.5 },
        armadillo: { width: 30, height: 10, offsetX: 0, offsetY: 22, alpha: 0.5 },
        
        // Cave enemies shadows
        slime: { width: 35, height: 10, offsetX: 0, offsetY: 30, alpha: 0.5 },
        kobold: { width: 38, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        brainmole: { width: 25, height: 8, offsetX: 0, offsetY: 20, alpha: 0.5 },
        intellectdevourer: { width: 25, height: 8, offsetX: 0, offsetY: 20, alpha: 0.5 },
        bloboid: { width: 35, height: 10, offsetX: 0, offsetY: 25, alpha: 0.5 },
        
        // Desert/Lava enemies shadows
        fireworm: { width: 45, height: 12, offsetX: 0, offsetY: 35, alpha: 0.5 },
        summoner: { width: 50, height: 15, offsetX: 0, offsetY: 50, alpha: 0.5 },
        soul: { width: 40, height: 12, offsetX: 0, offsetY: 40, alpha: 0.4 },
        fireslime: { width: 35, height: 12, offsetX: 0, offsetY: 30, alpha: 0.5 },
        orangegolem: { width: 60, height: 18, offsetX: 0, offsetY: 40, alpha: 0.6 },
        
        // Other enemies shadows
        sorcerer: { width: 45, height: 15, offsetX: 0, offsetY: 45, alpha: 0.5 },
        
        // Flying enemies have offset shadows
        bat: { width: 40, height: 10, offsetX: 0, offsetY: 60, alpha: 0.3 },
        darkbat: { width: 35, height: 8, offsetX: 0, offsetY: 50, alpha: 0.3 },
        flyingdemon: { width: 45, height: 12, offsetX: 0, offsetY: 55, alpha: 0.3 },
        
        // Bosses have large shadows
        'obelisk-boss': { width: 120, height: 30, offsetX: 0, offsetY: 80, alpha: 0.6 },
        'sand-obelisk-boss': { width: 120, height: 30, offsetX: 0, offsetY: 80, alpha: 0.6 },
        'demon-slime-boss': { width: 80, height: 20, offsetX: 0, offsetY: 50, alpha: 0.6 },
        'eyelor': { width: 90, height: 25, offsetX: 0, offsetY: 60, alpha: 0.5 },
        'nekros': { width: 70, height: 20, offsetX: 0, offsetY: 55, alpha: 0.6 },
        'voidkin': { width: 60, height: 18, offsetX: 0, offsetY: 50, alpha: 0.6 },
        'kingNothing': { width: 70, height: 20, offsetX: 0, offsetY: 55, alpha: 0.6 },
        'archer-boss': { width: 50, height: 15, offsetX: 0, offsetY: 45, alpha: 0.5 }
    },
    
    // Helper function to apply hitbox configuration
    applyHitbox: function(enemy, enemyType) {
        const config = this.hitboxes[enemyType];
        if (config) {
            enemy.body.setSize(config.width, config.height);
            enemy.body.setOffset(config.offsetX, config.offsetY);
            return true;
        }
        return false;
    },
    
    // Helper function to get shadow configuration
    getShadow: function(enemyType) {
        return this.shadows[enemyType] || this.shadows.default;
    },
    
    // Update configuration from sprite editor export
    updateFromEditor: function(editorData) {
        if (editorData.hitboxes) {
            Object.assign(this.hitboxes, editorData.hitboxes);
        }
        if (editorData.shadows) {
            Object.assign(this.shadows, editorData.shadows);
        }
    }
};

    // Make available globally if in browser/Electron
    if (typeof window !== 'undefined') {
        window.hitboxConfig = hitboxConfig;
    }

    // Export for Node.js/require
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = hitboxConfig;
    }
} // End of if (typeof hitboxConfig === 'undefined')