// Hitbox and Shadow Configuration for Enemies
// This file is generated by the sprite editor and loaded by the game
// Last updated: 2025-10-12T22:29:49.953Z

console.log('hitbox-config.js is loading...');

// Check if hitboxConfig already exists to avoid redeclaration
if (typeof hitboxConfig === 'undefined') {
    console.log('Creating hitboxConfig object...');
    var hitboxConfig = {
    loaded: false,
    
    // Load configuration (called when game starts)
    load: function() {
        this.loaded = true;
        console.log('Hitbox configuration loaded');
        console.log('Available scales:', this.scales);
        console.log('Available hitboxes:', Object.keys(this.hitboxes));
        return true;
    },
    
    // Flip configurations - used for initial sprite orientation
    flips: {
            "grim": {
                    "flipX": false,
                    "flipY": false
            },
            "test": {
                    "flipX": true,
                    "flipY": false
            },
            "orb": {
                    "flipX": true,
                    "flipY": false
            }
    },
    
    // Scale configurations for sprites
    scales: {
            "wizard": 1,
            "orb": 1,
            "grim": 1.3,
            "blip": 2.7,
            "tree": 1.2,
            "bat": 0.8,
            "mushroom": 0.7,
            "giantfly": 2,
            "squirrel": 2,
            "redpanda": 2,
            "slime": 1,
            "golem": 1.5,
            "golem-blue": 1.5,
            "golem-orange": 1.5,
            "kobold": 0.6,
            "brainmole": 2,
            "intellectdevourer": 1.8,
            "bloboid": 1.5,
            "cobra": 2,
            "cactuse": 4.8,
            "fireworm": 1.2,
            "summoner": 0.8,
            "fireslime": 1,
            "orangegolem": 1.5,
            "castle-knight": 1.4,
            "castle-rogue": 1.8,
            "castle-soldier": 1.4,
            "castle-bladekeeper": 1.1,
            "castle-squire": 1.5,
            "yellowskeleton": 1,
            "clubimp": 3,
            "axeimp": 3,
            "wraith": 1.5,
            "flyingdemon": 0.91,
            "darkbat": 1.2,
            "obelisk-boss": 2,
            "archer-boss": 2.25,
            "demon-slime-boss": 1.75,
            "eyelor-boss": 2,
            "nekros-boss": 1.8
    },
    
    // Hitbox configurations for each enemy type
    hitboxes: {
            "": {
                    "": 0
            },
            "golem-blue": {
                    "": 10
            },
            "golem-orange": {
                    "": 10
            },
            "castle-knight": {
                    "": 100
            },
            "castle-rogue": {
                    "": 4
            },
            "castle-soldier": {
                    "": 72
            },
            "castle-bladekeeper": {
                    "": 89
            },
            "castle-squire": {
                    "": 80
            },
            "obelisk-boss": {
                    "": 50
            },
            "archer-boss": {
                    "": 40
            },
            "demon-slime-boss": {
                    "": 40
            },
            "eyelor": {
                    "": 50
            },
            "eyelor-boss": {
                    "": 50
            },
            "nekros": {
                    "": 30
            },
            "nekros-boss": {
                    "": 30
            },
            "voidkin": {
                    "": 20
            },
            "kingNothing": {
                    "": 20
            },
            "blip": {
                    "": 1
            },
            "orb": {
                    "": 17
            },
            "wizard": {
                    "": 15
            },
            "grim": {
                    "": 15
            },
            "archer-projectile": {
                    "": 8
            },
            "waterball-projectile": {
                    "": 22
            },
            "fireball-projectile": {
                    "": 22
            },
            "void-ball": {
                    "": 17
            },
            "lightning-orb": {
                    "": 22
            },
            "test": {
                    "width": 50,
                    "height": 50,
                    "offsetX": 10,
                    "offsetY": 10
            }
    },
    
    // Shadow configurations for each enemy type
    shadows: {
            "": {
                    "": 0.3
            },
            "castle-bladekeeper": {
                    "": 89
            },
            "golem-blue": {
                    "": 10
            },
            "golem-orange": {
                    "": 10
            },
            "castle-knight": {
                    "": 100
            },
            "castle-rogue": {
                    "": 4
            },
            "castle-soldier": {
                    "": 72
            },
            "castle-squire": {
                    "": 80
            },
            "obelisk-boss": {
                    "": 50
            },
            "sand-obelisk-boss": {
                    "": 0.6
            },
            "demon-slime-boss": {
                    "": 40
            },
            "eyelor": {
                    "": 50
            },
            "eyelor-boss": {
                    "": 50
            },
            "nekros": {
                    "": 30
            },
            "nekros-boss": {
                    "": 30
            },
            "voidkin": {
                    "": 20
            },
            "kingNothing": {
                    "": 20
            },
            "archer-boss": {
                    "": 40
            }
    },
    
    // Helper function to get scale configuration
    getScale: function(spriteType) {
        return this.scales[spriteType] || 1.0;
    },
    
    // Helper function to apply scale
    applyScale: function(sprite, spriteType) {
        const scale = this.getScale(spriteType);
        console.log(`[HITBOX CONFIG] Applying scale for ${spriteType}: ${scale}`);
        console.log(`[HITBOX CONFIG] Sprite scale before: ${sprite.scaleX}`);
        sprite.setScale(scale);
        console.log(`[HITBOX CONFIG] Sprite scale after: ${sprite.scaleX}`);
        return scale;
    },
    
    // Helper function to apply hitbox configuration
    applyHitbox: function(enemy, enemyType) {
        const config = this.hitboxes[enemyType];
        if (config) {
            console.log(`[HITBOX] Applying for ${enemyType}:`, config);
            console.log(`[HITBOX] Sprite info - Scale: ${enemy.scaleX}, Origin: (${enemy.originX}, ${enemy.originY})`);
            console.log(`[HITBOX] Sprite dimensions - Width: ${enemy.width}, Height: ${enemy.height}`);
            console.log(`[HITBOX] Display dimensions - Width: ${enemy.displayWidth}, Height: ${enemy.displayHeight}`);
            
            // The sprite editor saves offsets in unscaled sprite coordinates
            // Phaser's body.setOffset() always uses unscaled coordinates
            // DO NOT divide by scale - apply directly
            enemy.body.setSize(config.width, config.height);
            enemy.body.setOffset(config.offsetX, config.offsetY);
            
            console.log(`[HITBOX] Applied - Size: ${config.width}x${config.height}, Direct offset: (${config.offsetX}, ${config.offsetY})`);
            console.log(`[HITBOX] Body position - X: ${enemy.body.x}, Y: ${enemy.body.y}`);
            return true;
        }
        console.log(`[HITBOX] No config found for ${enemyType}`);
        return false;
    },
    
    // Helper function to get shadow configuration
    getShadow: function(enemyType) {
        return this.shadows[enemyType] || this.shadows.default;
    },
    
    // Update configuration from sprite editor export
    updateFromEditor: function(editorData) {
        if (editorData.scales) {
            Object.assign(this.scales, editorData.scales);
        }
        if (editorData.hitboxes) {
            Object.assign(this.hitboxes, editorData.hitboxes);
        }
        if (editorData.shadows) {
            Object.assign(this.shadows, editorData.shadows);
        }
    }
};

    // Make available globally if in browser/Electron
    if (typeof window !== 'undefined') {
        window.hitboxConfig = hitboxConfig;
    }

    // Export for Node.js/require
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = hitboxConfig;
    }
    
    console.log('hitboxConfig created successfully');
    console.log('Grim hitbox:', hitboxConfig.hitboxes.grim);
} else {
    console.log('hitboxConfig already exists, skipping creation');
} // End of if (typeof hitboxConfig === 'undefined')

console.log('hitbox-config.js finished loading');
console.log('Flip configuration for grim:', hitboxConfig.flips.grim);